gcloud:
  projectId: ${GCP_PROJECT_ID:#{'test'}}
contact:
  firestore:
    collection: contacts
  api:
    base-path: /api/v1/contacts
pipeline:
  firestore:
    collection: pipelines
  api:
    base-path: /api/v1/pipelines
